"""
atlas_schema.py — MongoDB Atlas collection schemas and index setup

Run once to create indexes:
    python atlas_schema.py

Collections:
    cdvae.users       — user accounts
    cdvae.structures  — generated crystal structures per user
"""

import os
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv 

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
MONGO_DB  = os.getenv("MONGO_DB",  "cdvae")


# ══════════════════════════════════════════════════════════════════════════════
#  SCHEMA DOCUMENTATION
#
#  MongoDB is schemaless, but here is the exact shape of every document
#  your application writes. Use this as reference for Atlas Data Explorer.
# ══════════════════════════════════════════════════════════════════════════════

"""
────────────────────────────────────────────────────────────────
COLLECTION: users
────────────────────────────────────────────────────────────────
{
    "_id":           ObjectId,        // auto-generated by Atlas
    "username":      str,             // unique, 3-32 chars
    "email":         str | null,      // optional
    "password_hash": str,             // bcrypt hash, never plain text
    "created_at":    ISODate,         // UTC datetime
    "last_login":    ISODate          // updated on every login
}

Example document:
{
    "_id": ObjectId("665a1b2c3d4e5f6a7b8c9d0e"),
    "username": "alice",
    "email": "alice@example.com",
    "password_hash": "$2b$12$...",
    "created_at": ISODate("2024-06-01T12:00:00Z"),
    "last_login":  ISODate("2024-06-05T09:30:00Z")
}

────────────────────────────────────────────────────────────────
COLLECTION: structures
────────────────────────────────────────────────────────────────
{
    "_id":                ObjectId,         // auto-generated
    "username":           str,              // owner — from JWT, not client input

    // ── Generation context ─────────────────────────────────
    "label":              str | null,       // e.g. "Fe2O3"
    "requested_elements": [str],            // e.g. ["Fe", "O"]
    "temperature":        float,            // 0.5 / 0.8 / 1.0
    "created_at":         ISODate,          // UTC save time

    // ── Model outputs (raw from generate.py) ───────────────
    "n_atoms":            int,              // total atoms in unit cell
    "symbols":            [str],            // per-atom element symbols
    "atom_types":         [int],            // per-atom atomic numbers
    "frac_coords":        [[float]],        // (N, 3) fractional coordinates
    "cartesian":          [[float]],        // (N, 3) cartesian coords in Å
    "lattice":            [[float]],        // (3, 3) lattice matrix, row vectors
    "abc":                [float],          // [a, b, c] lattice lengths in Å
    "angles":             [float],          // [α, β, γ] in degrees (default 90,90,90)

    // ── Predicted properties ───────────────────────────────
    "energy":             float,            // formation energy eV/atom
    "ehull":              float,            // energy above convex hull eV/atom
    "band_gap":           float,            // band gap in eV

    // ── Cluster filter metadata (set by frontend) ──────────
    "cluster_n_atoms":    int | null,       // atoms after outlier removal
    "cluster_symbols":    [str] | null,     // element symbols after filtering
    "had_bonds":          bool | null,      // whether bonds were detected
    "dropped_atoms":      int | null        // number of outlier atoms removed
}
"""


# ══════════════════════════════════════════════════════════════════════════════
#  INDEX SETUP
#  Run this once after creating your Atlas cluster.
# ══════════════════════════════════════════════════════════════════════════════

async def create_indexes():
    client = AsyncIOMotorClient(MONGO_URI)
    db     = client[MONGO_DB]

    print(f"Connecting to Atlas: {MONGO_DB}")

    # ── users collection ──────────────────────────────────────────────────────
    # Unique index on username — enforced at DB level, not just app level
    await db["users"].create_index(
        "username",
        unique=True,
        name="username_unique"
    )
    print("✓  users.username  — unique index")

    # Optional: unique sparse index on email (sparse = allows multiple null)
    await db["users"].create_index(
        "email",
        unique=True,
        sparse=True,
        name="email_unique_sparse"
    )
    print("✓  users.email     — unique sparse index")

    # ── structures collection ─────────────────────────────────────────────────
    # Compound index: filter by user + sort by time — covers GET /structures
    await db["structures"].create_index(
        [("username", 1), ("created_at", -1)],
        name="username_created_at"
    )
    print("✓  structures.(username, created_at) — compound index")

    # Index for delete by label + username
    await db["structures"].create_index(
        [("username", 1), ("label", 1)],
        name="username_label"
    )
    print("✓  structures.(username, label) — compound index")

    # Index for querying by element composition
    await db["structures"].create_index(
        "requested_elements",
        name="requested_elements"
    )
    print("✓  structures.requested_elements — multikey index")

    print("\nAll indexes created successfully.")
    client.close()


if __name__ == "__main__":
    asyncio.run(create_indexes())
