/**
 * json_to_cif.js
 * Convert a structure JSON object (from /generate) to a CIF string.
 *
 * Input shape:
 * {
 *   symbols:     ['Fe', 'O', ...],
 *   frac_coords: [[x,y,z], ...],
 *   lattice:     [[a0,a1,a2],[b0,b1,b2],[c0,c1,c2]],  // row vectors in Å
 *   energy, ehull, band_gap, n_atoms   (optional — written as comments)
 * }
 */
function latticeToCellParams(lat) {
  const norm = v => Math.sqrt(v[0]**2 + v[1]**2 + v[2]**2);
  const dot  = (u, v) => u[0]*v[0] + u[1]*v[1] + u[2]*v[2];
  const [A, B, C] = lat;
  const a = norm(A), b = norm(B), c = norm(C);
  const toDeg = r => r * 180 / Math.PI;
  const clamp = x => Math.min(1, Math.max(-1, x));
  return {
    a, b, c,
    alpha: toDeg(Math.acos(clamp(dot(B,C)/(b*c)))),
    beta:  toDeg(Math.acos(clamp(dot(A,C)/(a*c)))),
    gamma: toDeg(Math.acos(clamp(dot(A,B)/(a*b)))),
  };
}

function structureJsonToCIF(s, opts = {}) {
  const { symbols, frac_coords, lattice, energy, ehull, band_gap } = s;
  if (!symbols || !frac_coords || !lattice)
    throw new Error('Missing required fields: symbols, frac_coords, lattice');

  const { a, b, c, alpha, beta, gamma } = latticeToCellParams(lattice);

  // Build reduced formula for the data block name
  const cnt = {};
  symbols.forEach(sym => cnt[sym] = (cnt[sym]||0)+1);
  const formula = Object.entries(cnt)
    .sort(([a],[b]) => a.localeCompare(b))
    .map(([el,n]) => el + (n>1?n:''))
    .join('');

  const dataName   = (opts.label || formula).replace(/\s+/g,'_');
  const spaceGroup = opts.spaceGroup || 'P 1';

  const lines = [
    `data_${dataName}`,
    '',
    `# Generated by CDVAE`,
    energy   !== undefined ? `# Formation energy:  ${energy.toFixed(4)} eV/atom`       : null,
    ehull    !== undefined ? `# Energy above hull: ${(ehull*1000).toFixed(2)} meV/atom` : null,
    band_gap !== undefined ? `# Band gap:          ${band_gap.toFixed(4)} eV`           : null,
    '',
    `_cell_length_a                  ${a.toFixed(4)}`,
    `_cell_length_b                  ${b.toFixed(4)}`,
    `_cell_length_c                  ${c.toFixed(4)}`,
    `_cell_angle_alpha               ${alpha.toFixed(4)}`,
    `_cell_angle_beta                ${beta.toFixed(4)}`,
    `_cell_angle_gamma               ${gamma.toFixed(4)}`,
    '',
    `_symmetry_space_group_name_H-M  '${spaceGroup}'`,
    `_symmetry_Int_Tables_number     1`,
    '',
    `_chemical_formula_sum           '${formula}'`,
    `_cell_formula_units_Z           1`,
    '',
    'loop_',
    '_atom_site_label',
    '_atom_site_type_symbol',
    '_atom_site_fract_x',
    '_atom_site_fract_y',
    '_atom_site_fract_z',
    '_atom_site_occupancy',
  ].filter(l => l !== null);

  const elIdx = {};
  for (let i = 0; i < symbols.length; i++) {
    const sym = symbols[i];
    elIdx[sym] = (elIdx[sym]||0)+1;
    const [fx, fy, fz] = frac_coords[i];
    const wrap = x => (((x % 1) + 1) % 1).toFixed(5);
    lines.push(`${(sym+elIdx[sym]).padEnd(6)} ${sym.padEnd(3)} ${wrap(fx)}  ${wrap(fy)}  ${wrap(fz)}  1.0000`);
  }

  lines.push('', '# end of data');
  return lines.join('\n');
}

// Works in both browser (window.structureJsonToCIF) and Node.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { structureJsonToCIF, latticeToCellParams };
} else {
  window.structureJsonToCIF = structureJsonToCIF;
}