
"""
visualize_3d.py — Interactive 3D Crystal Structure Viewer
==========================================================
Reads the .cif file generated by Generate_fixed.py and opens
an interactive 3D viewer in your Kaggle/Jupyter notebook.

Usage (in a Kaggle cell):
    from visualize_3d import show_crystal
    show_crystal("generated/sample_1.cif")

    # Or pass the result dict directly (no file needed):
    show_crystal(result=results[0])

Controls in the viewer:
    Left-drag  → rotate
    Right-drag → pan
    Scroll     → zoom
    Click atom → show element + position info
"""

import json
import math
import numpy as np
from IPython.display import display, HTML


# ── Element data: color + atomic radius ──────────────────────────────────────
ELEMENT_DATA = {
    "H":  {"color": "#FFFFFF", "r": 0.31, "name": "Hydrogen"},
    "He": {"color": "#D9FFFF", "r": 0.28, "name": "Helium"},
    "Li": {"color": "#CC80FF", "r": 1.28, "name": "Lithium"},
    "Be": {"color": "#C2FF00", "r": 0.96, "name": "Beryllium"},
    "B":  {"color": "#FFB5B5", "r": 0.84, "name": "Boron"},
    "C":  {"color": "#909090", "r": 0.77, "name": "Carbon"},
    "N":  {"color": "#3050F8", "r": 0.75, "name": "Nitrogen"},
    "O":  {"color": "#FF0D0D", "r": 0.73, "name": "Oxygen"},
    "F":  {"color": "#90E050", "r": 0.71, "name": "Fluorine"},
    "Na": {"color": "#AB5CF2", "r": 1.66, "name": "Sodium"},
    "Mg": {"color": "#8AFF00", "r": 1.41, "name": "Magnesium"},
    "Al": {"color": "#BFA6A6", "r": 1.21, "name": "Aluminium"},
    "Si": {"color": "#F0C8A0", "r": 1.11, "name": "Silicon"},
    "P":  {"color": "#FF8000", "r": 1.07, "name": "Phosphorus"},
    "S":  {"color": "#FFFF30", "r": 1.05, "name": "Sulfur"},
    "Cl": {"color": "#1FF01F", "r": 1.02, "name": "Chlorine"},
    "K":  {"color": "#8F40D4", "r": 2.03, "name": "Potassium"},
    "Ca": {"color": "#3DFF00", "r": 1.76, "name": "Calcium"},
    "Sc": {"color": "#E6E6E6", "r": 1.70, "name": "Scandium"},
    "Ti": {"color": "#BFC2C7", "r": 1.60, "name": "Titanium"},
    "V":  {"color": "#A6A6AB", "r": 1.53, "name": "Vanadium"},
    "Cr": {"color": "#8A99C7", "r": 1.39, "name": "Chromium"},
    "Mn": {"color": "#9C7AC7", "r": 1.50, "name": "Manganese"},
    "Fe": {"color": "#E06633", "r": 1.32, "name": "Iron"},
    "Co": {"color": "#F090A0", "r": 1.26, "name": "Cobalt"},
    "Ni": {"color": "#50D050", "r": 1.24, "name": "Nickel"},
    "Cu": {"color": "#C88033", "r": 1.32, "name": "Copper"},
    "Zn": {"color": "#7D80B0", "r": 1.22, "name": "Zinc"},
    "Ga": {"color": "#C28F8F", "r": 1.22, "name": "Gallium"},
    "Ge": {"color": "#668F8F", "r": 1.22, "name": "Germanium"},
    "As": {"color": "#BD80E3", "r": 1.19, "name": "Arsenic"},
    "Se": {"color": "#FFA100", "r": 1.20, "name": "Selenium"},
    "Br": {"color": "#A62929", "r": 1.20, "name": "Bromine"},
    "Sr": {"color": "#00FF00", "r": 1.95, "name": "Strontium"},
    "Y":  {"color": "#94FFFF", "r": 1.90, "name": "Yttrium"},
    "Zr": {"color": "#94E0E0", "r": 1.75, "name": "Zirconium"},
    "Nb": {"color": "#73C2C9", "r": 1.64, "name": "Niobium"},
    "Mo": {"color": "#54B5B5", "r": 1.54, "name": "Molybdenum"},
    "Pd": {"color": "#006985", "r": 1.39, "name": "Palladium"},
    "Ag": {"color": "#C0C0C0", "r": 1.45, "name": "Silver"},
    "Ba": {"color": "#00C900", "r": 2.15, "name": "Barium"},
    "La": {"color": "#70D4FF", "r": 2.07, "name": "Lanthanum"},
    "Ce": {"color": "#FFFFC7", "r": 2.04, "name": "Cerium"},
    "Hf": {"color": "#4DC2FF", "r": 1.75, "name": "Hafnium"},
    "W":  {"color": "#2194D6", "r": 1.62, "name": "Tungsten"},
    "Pt": {"color": "#D0D0E0", "r": 1.39, "name": "Platinum"},
    "Au": {"color": "#FFD123", "r": 1.44, "name": "Gold"},
    "Pb": {"color": "#575961", "r": 1.75, "name": "Lead"},
    "Bi": {"color": "#9E4FB5", "r": 1.70, "name": "Bismuth"},
}
DEFAULT_ELEMENT = {"color": "#FF69B4", "r": 1.20, "name": "Unknown"}


# ── CIF parser ────────────────────────────────────────────────────────────────

def parse_cif(filepath):
    """Parse minimal CIF file → lattice matrix + atom list."""
    params = {}
    atoms  = []
    in_loop = False
    cols    = []

    with open(filepath) as f:
        lines = f.readlines()

    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        # Lattice parameters
        for key in ["_cell_length_a", "_cell_length_b", "_cell_length_c",
                    "_cell_angle_alpha", "_cell_angle_beta", "_cell_angle_gamma"]:
            if line.startswith(key):
                try:
                    params[key] = float(line.split()[-1].split("(")[0])
                except:
                    pass

        if "loop_" in line:
            in_loop = True
            cols    = []
            continue

        if in_loop:
            if line.startswith("_atom_site"):
                cols.append(line.strip())
                continue
            elif line.startswith("_") :
                in_loop = False
                cols    = []
                continue
            elif cols:
                parts = line.split()
                if len(parts) >= len(cols) and len(cols) >= 4:
                    try:
                        row = dict(zip(cols, parts))
                        sym = row.get("_atom_site_type_symbol",
                              row.get("_atom_site_label", "X"))
                        sym = "".join(c for c in sym if c.isalpha())[:2].capitalize()
                        x   = float(row.get("_atom_site_fract_x", 0))
                        y   = float(row.get("_atom_site_fract_y", 0))
                        z   = float(row.get("_atom_site_fract_z", 0))
                        atoms.append({"sym": sym, "frac": [x, y, z]})
                    except:
                        pass

    # Build lattice matrix from a,b,c,α,β,γ
    a  = params.get("_cell_length_a", 4.0)
    b  = params.get("_cell_length_b", 4.0)
    c  = params.get("_cell_length_c", 4.0)
    al = math.radians(params.get("_cell_angle_alpha", 90.0))
    be = math.radians(params.get("_cell_angle_beta",  90.0))
    ga = math.radians(params.get("_cell_angle_gamma", 90.0))

    sg = math.sin(ga)
    cg = math.cos(ga)
    cb = math.cos(be)
    ca = math.cos(al)

    # Standard crystallographic → Cartesian conversion
    v  = math.sqrt(max(1 - ca**2 - cb**2 - cg**2 + 2*ca*cb*cg, 1e-10))
    L  = [
        [a,         b*cg,                      c*cb],
        [0,         b*sg,                      c*(ca - cb*cg)/max(sg, 1e-10)],
        [0,         0,                         c*v/max(sg, 1e-10)],
    ]

    # Fractional → Cartesian
    cart_atoms = []
    for atom in atoms:
        fx, fy, fz = atom["frac"]
        cx = L[0][0]*fx + L[0][1]*fy + L[0][2]*fz
        cy =              L[1][1]*fy + L[1][2]*fz
        cz =                           L[2][2]*fz
        cart_atoms.append({
            "sym"  : atom["sym"],
            "pos"  : [round(cx, 4), round(cy, 4), round(cz, 4)],
            "frac" : [round(fx, 4), round(fy, 4), round(fz, 4)],
        })

    # Lattice vectors for unit-cell wireframe
    lattice_vecs = [
        [round(L[0][0], 4), 0,                  0                 ],
        [round(L[0][1], 4), round(L[1][1], 4),  0                 ],
        [round(L[0][2], 4), round(L[1][2], 4),  round(L[2][2], 4)],
    ]

    return {
        "atoms"       : cart_atoms,
        "lattice_vecs": lattice_vecs,
        "params"      : {
            "a": a, "b": b, "c": c,
            "alpha": math.degrees(al),
            "beta" : math.degrees(be),
            "gamma": math.degrees(ga),
        },
    }


def result_to_scene(result):
    """Convert generate() result dict → scene dict (bypasses CIF)."""
    L    = result["lattice"]
    atoms = []
    for sym, pos, frac in zip(result["symbols"],
                               result["cartesian"],
                               result["frac_coords"]):
        atoms.append({
            "sym" : sym,
            "pos" : [round(float(p), 4) for p in pos],
            "frac": [round(float(f), 4) for f in frac],
        })

    lattice_vecs = [
        [round(float(L[0][0]), 4), round(float(L[1][0]), 4), round(float(L[2][0]), 4)],
        [round(float(L[0][1]), 4), round(float(L[1][1]), 4), round(float(L[2][1]), 4)],
        [round(float(L[0][2]), 4), round(float(L[1][2]), 4), round(float(L[2][2]), 4)],
    ]

    a = float(np.linalg.norm(L[0]))
    b = float(np.linalg.norm(L[1]))
    c = float(np.linalg.norm(L[2]))
    cos_al = float(np.dot(L[1], L[2]) / (b * c + 1e-8))
    cos_be = float(np.dot(L[0], L[2]) / (a * c + 1e-8))
    cos_ga = float(np.dot(L[0], L[1]) / (a * b + 1e-8))

    return {
        "atoms"       : atoms,
        "lattice_vecs": lattice_vecs,
        "params": {
            "a": round(a, 3), "b": round(b, 3), "c": round(c, 3),
            "alpha": round(math.degrees(math.acos(np.clip(cos_al, -1, 1))), 2),
            "beta" : round(math.degrees(math.acos(np.clip(cos_be, -1, 1))), 2),
            "gamma": round(math.degrees(math.acos(np.clip(cos_ga, -1, 1))), 2),
        },
        "energy"  : result.get("energy", None),
        "ehull"   : result.get("ehull", None),
        "band_gap": result.get("band_gap", None),
    }


# ── HTML / Three.js viewer ────────────────────────────────────────────────────

HTML_TEMPLATE = r"""
<div id="cdvae-viewer-{uid}" style="width:100%;font-family:monospace;">

<style>
  #cv-{uid} {{
    width:100%; height:520px; border-radius:10px;
    background:#0d1117; display:block; cursor:grab; position:relative;
  }}
  #cv-{uid}:active {{ cursor:grabbing; }}
  .cv-info-{uid} {{
    position:absolute; bottom:12px; left:12px;
    background:rgba(13,17,23,0.85); color:#c9d1d9;
    padding:8px 12px; border-radius:7px;
    font-size:12px; line-height:1.6; pointer-events:none;
    border:1px solid rgba(255,255,255,0.08);
  }}
  .cv-tooltip-{uid} {{
    position:absolute; display:none;
    background:rgba(13,17,23,0.92); color:#e6edf3;
    padding:6px 10px; border-radius:6px; font-size:12px;
    border:1px solid rgba(255,255,255,0.12); pointer-events:none;
  }}
  .cv-legend-{uid} {{
    position:absolute; top:12px; right:12px;
    background:rgba(13,17,23,0.85); color:#c9d1d9;
    padding:8px 12px; border-radius:7px; font-size:12px;
    border:1px solid rgba(255,255,255,0.08); max-width:160px;
  }}
  .cv-legend-{uid} .dot {{
    display:inline-block; width:10px; height:10px;
    border-radius:50%; margin-right:6px; vertical-align:middle;
  }}
  .cv-controls-{uid} {{
    display:flex; gap:8px; padding:8px 0 4px; flex-wrap:wrap;
    align-items:center;
  }}
  .cv-btn-{uid} {{
    background:#161b22; color:#c9d1d9; border:1px solid #30363d;
    border-radius:6px; padding:5px 12px; font-size:12px;
    cursor:pointer; font-family:monospace;
  }}
  .cv-btn-{uid}:hover {{ background:#21262d; }}
  .cv-btn-{uid}.active {{ background:#1f6feb; border-color:#388bfd; color:#fff; }}
  .cv-prop-{uid} {{
    display:flex; gap:10px; padding:6px 0; flex-wrap:wrap;
  }}
  .cv-chip-{uid} {{
    background:#161b22; border:1px solid #30363d;
    border-radius:20px; padding:4px 12px; font-size:12px; color:#c9d1d9;
  }}
  .cv-chip-{uid} span {{ color:#58a6ff; font-weight:bold; }}
</style>

<canvas id="cv-{uid}"></canvas>
<div class="cv-info-{uid}" id="cv-info-{uid}">
  {info_html}
</div>
<div class="cv-tooltip-{uid}" id="cv-tooltip-{uid}"></div>
<div class="cv-legend-{uid}" id="cv-legend-{uid}"></div>

<div class="cv-controls-{uid}">
  <button class="cv-btn-{uid} active" id="cv-bonds-{uid}" onclick="cvToggleBonds_{uid}()">Bonds</button>
  <button class="cv-btn-{uid} active" id="cv-cell-{uid}"  onclick="cvToggleCell_{uid}()">Unit cell</button>
  <button class="cv-btn-{uid}" id="cv-axes-{uid}"  onclick="cvToggleAxes_{uid}()">Axes</button>
  <button class="cv-btn-{uid}" onclick="cvReset_{uid}()">Reset view</button>
  <button class="cv-btn-{uid}" onclick="cvAuto_{uid}()">Auto-rotate</button>
</div>

<div class="cv-prop-{uid}">
{prop_chips}
</div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script>
(function() {{

const SCENE_DATA = {scene_json};
const ELEM_DATA  = {elem_json};
const UID = "{uid}";

const canvas   = document.getElementById("cv-" + UID);
const tooltip  = document.getElementById("cv-tooltip-" + UID);
const legendEl = document.getElementById("cv-legend-" + UID);

const renderer = new THREE.WebGLRenderer({{ canvas, antialias: true, alpha: true }});
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(canvas.clientWidth, 520);
renderer.setClearColor(0x0d1117, 1);

const scene  = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(45, canvas.clientWidth / 520, 0.1, 1000);

// Centre of mass
const atoms = SCENE_DATA.atoms;
let cx=0, cy=0, cz=0;
atoms.forEach(a => {{ cx+=a.pos[0]; cy+=a.pos[1]; cz+=a.pos[2]; }});
cx/=atoms.length; cy/=atoms.length; cz/=atoms.length;

// Camera distance from bounding box
let maxR = 0;
atoms.forEach(a => {{
  const d = Math.sqrt((a.pos[0]-cx)**2+(a.pos[1]-cy)**2+(a.pos[2]-cz)**2);
  if(d>maxR) maxR=d;
}});
camera.position.set(cx, cy, cz + maxR*2.8);
camera.lookAt(cx, cy, cz);

// Lighting
scene.add(new THREE.AmbientLight(0xffffff, 0.55));
const dl = new THREE.DirectionalLight(0xffffff, 0.9);
dl.position.set(cx+10, cy+10, cz+10);
scene.add(dl);
const dl2 = new THREE.DirectionalLight(0x8ab4f8, 0.35);
dl2.position.set(cx-8, cy-6, cz-4);
scene.add(dl2);

// ── Atoms ────────────────────────────────────────────────────────────────────
const atomMeshes = [];
const elemPresent = {{}};

atoms.forEach((atom, idx) => {{
  const ed   = ELEM_DATA[atom.sym] || {{ color:"#FF69B4", r:1.2, name:"Unknown" }};
  const r    = Math.max(ed.r * 0.38, 0.18);
  const geo  = new THREE.SphereGeometry(r, 24, 18);
  const mat  = new THREE.MeshPhongMaterial({{
    color: new THREE.Color(ed.color),
    shininess: 80,
    specular: new THREE.Color(0x444444),
  }});
  const mesh = new THREE.Mesh(geo, mat);
  mesh.position.set(atom.pos[0]-cx, atom.pos[1]-cy, atom.pos[2]-cz);
  mesh.userData = {{ idx, sym: atom.sym, pos: atom.pos, frac: atom.frac, name: ed.name }};
  scene.add(mesh);
  atomMeshes.push(mesh);
  elemPresent[atom.sym] = ed.color;
}});

// ── Bond detection ───────────────────────────────────────────────────────────
const bondGroup = new THREE.Group();
scene.add(bondGroup);

function makeBonds() {{
  while(bondGroup.children.length) bondGroup.remove(bondGroup.children[0]);
  const BOND_SCALE = 1.15;
  for(let i=0; i<atoms.length; i++) {{
    for(let j=i+1; j<atoms.length; j++) {{
      const ai = atoms[i], aj = atoms[j];
      const ri = (ELEM_DATA[ai.sym]||{{r:1.2}}).r;
      const rj = (ELEM_DATA[aj.sym]||{{r:1.2}}).r;
      const thresh = (ri+rj) * BOND_SCALE;
      const dx=ai.pos[0]-aj.pos[0], dy=ai.pos[1]-aj.pos[1], dz=ai.pos[2]-aj.pos[2];
      const dist = Math.sqrt(dx*dx+dy*dy+dz*dz);
      if(dist < thresh && dist > 0.3) {{
        const mid = new THREE.Vector3(
          (ai.pos[0]+aj.pos[0])/2-cx,
          (ai.pos[1]+aj.pos[1])/2-cy,
          (ai.pos[2]+aj.pos[2])/2-cz,
        );
        const start = new THREE.Vector3(ai.pos[0]-cx, ai.pos[1]-cy, ai.pos[2]-cz);
        const end   = new THREE.Vector3(aj.pos[0]-cx, aj.pos[1]-cy, aj.pos[2]-cz);

        const dir = end.clone().sub(start).normalize();
        const up  = Math.abs(dir.y) < 0.99
          ? new THREE.Vector3(0,1,0)
          : new THREE.Vector3(1,0,0);

        // Half-bond from i to mid
        makeHalfBond(start, mid, ELEM_DATA[ai.sym]||{{color:"#FF69B4"}});
        makeHalfBond(mid, end, ELEM_DATA[aj.sym]||{{color:"#FF69B4"}});
      }}
    }}
  }}
}}

function makeHalfBond(from, to, ed) {{
  const dir  = to.clone().sub(from);
  const len  = dir.length();
  const geo  = new THREE.CylinderGeometry(0.07, 0.07, len, 8, 1);
  const mat  = new THREE.MeshPhongMaterial({{
    color: new THREE.Color(ed.color), shininess:40 }});
  const mesh = new THREE.Mesh(geo, mat);
  const mid  = from.clone().add(to).multiplyScalar(0.5);
  mesh.position.copy(mid);
  mesh.quaternion.setFromUnitVectors(
    new THREE.Vector3(0,1,0), dir.clone().normalize());
  bondGroup.add(mesh);
}}

makeBonds();

// ── Unit cell wireframe ───────────────────────────────────────────────────────
const cellGroup = new THREE.Group();
scene.add(cellGroup);

function makeCell() {{
  while(cellGroup.children.length) cellGroup.remove(cellGroup.children[0]);
  const v = SCENE_DATA.lattice_vecs;
  const A = new THREE.Vector3(v[0][0], v[0][1], v[0][2]);
  const B = new THREE.Vector3(v[1][0], v[1][1], v[1][2]);
  const C = new THREE.Vector3(v[2][0], v[2][1], v[2][2]);

  const O  = new THREE.Vector3(0,0,0);
  const OA = A.clone(), OB = B.clone(), OC = C.clone();
  const AB = A.clone().add(B);
  const AC = A.clone().add(C);
  const BC = B.clone().add(C);
  const ABC= A.clone().add(B).add(C);

  // Offset to atom centroid
  const off = new THREE.Vector3(-cx, -cy, -cz);
  const pts = [O,OA,OB,OC,AB,AC,BC,ABC].map(p => p.clone().add(off));

  const edges = [
    [0,1],[0,2],[0,3],
    [1,4],[1,5],[2,4],[2,6],[3,5],[3,6],
    [4,7],[5,7],[6,7],
  ];

  const mat = new THREE.LineBasicMaterial({{ color:0x58a6ff, transparent:true, opacity:0.5 }});
  edges.forEach(([a,b]) => {{
    const geo = new THREE.BufferGeometry().setFromPoints([pts[a], pts[b]]);
    cellGroup.add(new THREE.Line(geo, mat));
  }});
}}

makeCell();

// ── Axes helper ───────────────────────────────────────────────────────────────
const axesGroup = new THREE.Group();
axesGroup.visible = false;
scene.add(axesGroup);

(function() {{
  const origin = new THREE.Vector3(-cx, -cy, -cz);
  const scale  = maxR * 0.8;
  const axes   = [
    {{ dir:[1,0,0], color:0xff4444, label:"a" }},
    {{ dir:[0,1,0], color:0x44ff44, label:"b" }},
    {{ dir:[0,0,1], color:0x4488ff, label:"c" }},
  ];
  axes.forEach(ax => {{
    const end = new THREE.Vector3(...ax.dir).multiplyScalar(scale).add(origin);
    const geo = new THREE.BufferGeometry().setFromPoints([origin, end]);
    axesGroup.add(new THREE.Line(geo,
      new THREE.LineBasicMaterial({{ color: ax.color }})));
    // Arrow cone
    const coneGeo = new THREE.CylinderGeometry(0, 0.12, 0.3, 8);
    const coneMat = new THREE.MeshBasicMaterial({{ color: ax.color }});
    const cone    = new THREE.Mesh(coneGeo, coneMat);
    cone.position.copy(end);
    const dir = new THREE.Vector3(...ax.dir);
    cone.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0), dir);
    axesGroup.add(cone);
  }});
}})();

// ── Legend ────────────────────────────────────────────────────────────────────
let legendHtml = "<div style='font-size:11px;color:#8b949e;margin-bottom:4px'>Elements</div>";
Object.entries(elemPresent).forEach(([sym, color]) => {{
  const name = (ELEM_DATA[sym]||{{}}).name || sym;
  legendHtml += `<div style="margin:3px 0"><span class="dot" style="background:${{color}}"></span>${{sym}} — ${{name}}</div>`;
}});
legendEl.innerHTML = legendHtml;

// ── Mouse interaction ─────────────────────────────────────────────────────────
const raycaster = new THREE.Raycaster();
const mouse     = new THREE.Vector2();

canvas.addEventListener("mousemove", e => {{
  const rect = canvas.getBoundingClientRect();
  mouse.x =  ((e.clientX - rect.left) / rect.width)  * 2 - 1;
  mouse.y = -((e.clientY - rect.top)  / rect.height) * 2 + 1;
  raycaster.setFromCamera(mouse, camera);
  const hits = raycaster.intersectObjects(atomMeshes);
  if(hits.length) {{
    const d  = hits[0].object.userData;
    const ed = ELEM_DATA[d.sym] || {{}};
    tooltip.style.display = "block";
    tooltip.style.left    = (e.clientX - canvas.getBoundingClientRect().left + 12) + "px";
    tooltip.style.top     = (e.clientY - canvas.getBoundingClientRect().top  - 10) + "px";
    tooltip.innerHTML = `
      <b style="color:#58a6ff">${{d.sym}}</b> — ${{ed.name||d.sym}}<br>
      Atom #${{d.idx+1}}<br>
      Cart: (${{d.pos.map(v=>v.toFixed(3)).join(", ")}}) Å<br>
      Frac: (${{d.frac.map(v=>v.toFixed(3)).join(", ")}})
    `;
  }} else {{
    tooltip.style.display = "none";
  }}
}});

canvas.addEventListener("mouseleave", () => {{ tooltip.style.display="none"; }});

// ── Orbit controls (manual) ───────────────────────────────────────────────────
let isDragging=false, isPanning=false;
let prevX=0, prevY=0;
let phi=0, theta=0;
const target = new THREE.Vector3(0, 0, 0);
let radius = maxR * 2.8;

function updateCamera() {{
  const x = radius * Math.sin(phi) * Math.cos(theta);
  const y = radius * Math.cos(phi);
  const z = radius * Math.sin(phi) * Math.sin(theta);
  camera.position.set(x + target.x, y + target.y, z + target.z);
  camera.lookAt(target);
}}

canvas.addEventListener("mousedown", e => {{
  if(e.button===0) {{ isDragging=true; }}
  if(e.button===2) {{ isPanning=true;  }}
  prevX=e.clientX; prevY=e.clientY;
}});
window.addEventListener("mouseup", () => {{ isDragging=false; isPanning=false; }});
canvas.addEventListener("contextmenu", e => e.preventDefault());

window.addEventListener("mousemove", e => {{
  if(!isDragging && !isPanning) return;
  const dx = e.clientX - prevX;
  const dy = e.clientY - prevY;
  prevX=e.clientX; prevY=e.clientY;
  if(isDragging) {{
    theta -= dx * 0.01;
    phi    = Math.max(0.05, Math.min(Math.PI-0.05, phi - dy*0.01));
    updateCamera();
  }}
  if(isPanning) {{
    const right = new THREE.Vector3().crossVectors(
      camera.getWorldDirection(new THREE.Vector3()),
      camera.up
    ).normalize();
    const speed = radius * 0.002;
    target.addScaledVector(right, -dx * speed);
    target.y += dy * speed;
    updateCamera();
  }}
}});

canvas.addEventListener("wheel", e => {{
  radius = Math.max(1, Math.min(200, radius + e.deltaY * 0.05));
  updateCamera();
  e.preventDefault();
}}, {{ passive:false }});

// ── Toggle buttons ────────────────────────────────────────────────────────────
let bondsOn=true, cellOn=true, axesOn=false, autoRotate=false;

window["cvToggleBonds_"+UID] = function() {{
  bondsOn = !bondsOn;
  bondGroup.visible = bondsOn;
  document.getElementById("cv-bonds-"+UID).classList.toggle("active", bondsOn);
}};
window["cvToggleCell_"+UID] = function() {{
  cellOn = !cellOn;
  cellGroup.visible = cellOn;
  document.getElementById("cv-cell-"+UID).classList.toggle("active", cellOn);
}};
window["cvToggleAxes_"+UID] = function() {{
  axesOn = !axesOn;
  axesGroup.visible = axesOn;
  document.getElementById("cv-axes-"+UID).classList.toggle("active", axesOn);
}};
window["cvReset_"+UID] = function() {{
  phi=1.2; theta=0.8; radius=maxR*2.8;
  target.set(0,0,0); updateCamera();
}};
window["cvAuto_"+UID] = function() {{
  autoRotate = !autoRotate;
  document.getElementById("cv-axes-"+UID);
}};

// ── Render loop ───────────────────────────────────────────────────────────────
phi=1.2; theta=0.8;
updateCamera();

function animate() {{
  requestAnimationFrame(animate);
  if(autoRotate) {{ theta += 0.005; updateCamera(); }}
  renderer.render(scene, camera);
}}
animate();

}})();
</script>
"""


def show_crystal(filepath=None, result=None, title=None, height=520):
    """
    Show an interactive 3D crystal structure viewer inline in Jupyter/Kaggle.

    Args:
        filepath : path to a .cif file (e.g. "generated/sample_1.cif")
        result   : dict returned by model.generate() — use instead of filepath
        title    : optional title string
        height   : viewer height in px (default 520)
    """
    import uuid
    uid = uuid.uuid4().hex[:8]

    if result is not None:
        scene = result_to_scene(result)
    elif filepath is not None:
        scene = parse_cif(filepath)
        scene["energy"]   = None
        scene["ehull"]    = None
        scene["band_gap"] = None
    else:
        raise ValueError("Provide either filepath= or result=")

    # Info panel
    p = scene["params"]
    info_html = (
        f"<b>Lattice</b><br>"
        f"a={p['a']:.3f} b={p['b']:.3f} c={p['c']:.3f} Å<br>"
        f"α={p['alpha']:.1f}° β={p['beta']:.1f}° γ={p['gamma']:.1f}°<br>"
        f"Atoms: {len(scene['atoms'])}"
    )
    if title:
        info_html = f"<b style='color:#58a6ff'>{title}</b><br>" + info_html

    # Property chips
    prop_chips = ""
    if scene.get("energy") is not None:
        prop_chips += f'<div class="cv-chip-{uid}">Formation energy <span>{scene["energy"]:+.3f} eV/at</span></div>'
    if scene.get("ehull") is not None:
        e = scene["ehull"]
        stab = "Stable" if e < 0.025 else ("Metastable" if e < 0.1 else "Unstable")
        col  = "#3fb950" if e < 0.025 else ("#d29922" if e < 0.1 else "#f85149")
        prop_chips += f'<div class="cv-chip-{uid}">E above hull <span style="color:{col}">{e:+.4f} eV/at ({stab})</span></div>'
    if scene.get("band_gap") is not None:
        bg = scene["band_gap"]
        prop_chips += f'<div class="cv-chip-{uid}">Band gap <span>{bg:.3f} eV</span></div>'

    html = HTML_TEMPLATE.format(
        uid        = uid,
        scene_json = json.dumps(scene),
        elem_json  = json.dumps(ELEMENT_DATA),
        info_html  = info_html,
        prop_chips = prop_chips,
    )
    display(HTML(html))


# ── Convenience: show all results from generate() ────────────────────────────

def show_all(results, elements=None):
    """Show all structures from model.generate() in 3D, one after another."""
    for i, r in enumerate(results):
        comp = {}
        for s in r["symbols"]:
            comp[s] = comp.get(s, 0) + 1
        formula = "".join(f"{el}{n if n>1 else ''}" for el, n in sorted(comp.items()))
        t = f"Sample #{i+1} — {formula}"
        print(f"\n{'='*50}")
        print(f"  {t}")
        print(f"  Atoms: {r['n_atoms']}  |  "
              f"Energy: {r['energy']:+.3f} eV/at  |  "
              f"E_hull: {r['ehull']:+.4f} eV/at  |  "
              f"Band gap: {r['band_gap']:.3f} eV")
        print(f"{'='*50}")
        show_crystal(result=r, title=t)